### ISSUE TITLE
No error handling if axios call fails

### ISSUE THREAD

**Issue by pcon** [saltyshiomix/gfm-preview#1]
If the axios call fails (for my example my IP address what rate limited for an unauthenticated request) no feedback is given.  I think the code below should handle that case

```javascript
try {
      const response = await axios.post(apiUrl + '/markdown', { text, mode: 'gfm' })
      content = response.data
} catch (e) {
      content = e.response.data.message
}
```

**Comment by saltyshiomix** [comment]
Thank you for your reporting that!
(Rate limit is 5000 times per hour, so I missed it.)

I fixed it `gfm-preview@1.6.1` 👍
