### ISSUE TITLE
Add ability to set hostname for remote usage

### ISSUE THREAD

**Issue by pcon** [saltyshiomix/gfm-preview#2]
Currently the app assumes that you're using `localhost` as your hostname.  If you try to run it on a remote system, it loads but the HTML fails to pull in it's contents because it assumes everything is `localhost`.  By changing the `localhost` value to another hostname, I was able to get it to work remotely.  I would suggest that you do the same substitution that you do for `<!--TITLE-->` and allow the hostname to be passed in via the command line

**Comment by saltyshiomix** [comment]
I'm so sorry replying this issue so late(because I was in a hospital :<)

By the way, now latest `gfm-preview` can set hostname by yourself!

```bash
$ npm i -g gfm-preview@latest

# in this way, THIS computer's localhost:8080 is in public, and you can see from another computer :)
$ preview file.md --host 0.0.0.0 --port 8080
```

**Comment by pcon** [comment]
Awesome that works great! Hope everything is going well post hospital.
